// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyyE4Fhpehh70d40pXzVm0YTelfXr-_JQ',
    appId: '1:741033924561:web:238b8cbe63546397c1f2f0',
    messagingSenderId: '741033924561',
    projectId: 'gidihomes-ng',
    authDomain: 'gidihomes-ng.firebaseapp.com',
    storageBucket: 'gidihomes-ng.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhO2khM3Pg_d9k_HziDgVJLMuTC4MkCZA',
    appId: '1:741033924561:android:4d9c9da9c2258cdcc1f2f0',
    messagingSenderId: '741033924561',
    projectId: 'gidihomes-ng',
    storageBucket: 'gidihomes-ng.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf5fWD5p41nYiJ_iZYccbt4NPhE3BSF3s',
    appId: '1:741033924561:ios:82f486160a43b666c1f2f0',
    messagingSenderId: '741033924561',
    projectId: 'gidihomes-ng',
    storageBucket: 'gidihomes-ng.firebasestorage.app',
    iosBundleId: 'ng.gidihomes.gidiHomes',
  );
}
